name: Test, Build and Publilsh the ReJson Ruby Gem
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   if: github.event_name != 'release'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         bundler-cache: true

  #     - name: Run tests
  #       run: |
  #         bundle exec rspec

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v1

      - name: Build and publish gem
        uses: jstastny/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ant-money-advisors
